# Generated by Django 6.0.1 on 2026-01-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0010_alter_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='title_name',
            new_name='first_name',
        ),
    ]
